//Crow-Crow
const roles = {
'*Novice V* 🍄': 0,
'*Novice IV* 🍄': 2,
'*Novice III* 🍄': 4,
'*Novice II* 🍄': 6,
'*Novice I* 🍄': 8,
'*Student V* 🍹': 10,
'*Student IV* 🍹': 12,
'*Student III* 🍹': 14,
'*Student II* 🍹': 16,
'*Student I* 🍹': 18,
'*Intermediate V* 🥃': 20,
'*Intermediate IV* 🥃': 22,
'*Intermediate III* 🥃': 24,
'*Intermediate II* 🥃': 26,
'*Intermediate I* 🥃': 28,
'*Master V* ☁️': 30,
'*Master IV* ☁️': 32,
'*Master III* ☁️': 34,
'*Master II* ☁️': 36,
'*Master I* ☁️': 38,
'*Expert V* 🪐': 40,
'*Expert IV* 🪐': 42,
'*Expert III* 🪐': 44,
'*Expert II* 🪐': 46,
'*Expert I* 🪐': 48,
'*Genius V* 💧': 50,
'*Genius IV* 💧': 52,
'*Genius III* 💧': 54,
'*Genius II* 💧': 56,
'*Genius I* 💧': 58,
'*Superior V* 🍿': 60,
'*Superior IV* 🍿': 62,
'*Superior III* 🍿': 64,
'*Superior II* 🍿': 66,
'*Superior I* 🍿': 68,
'*Bot Expert V* 🌐': 70,
'*Bot Expert IV* 🌐': 72,
'*Bot Expert III* 🌐': 74,
'*Bot Expert II* 🌐': 76,
'*Bot Expert I* 🌐': 78,
'*Pro V* 💰': 80,
'*Pro IV* 💰': 82,
'*Pro III* 💰': 84,
'*Pro II* 💰': 86,
'*Pro I* 💰': 88,
'*Pro Superior V* 🎁': 90,
'*Pro Superior IV* 🎁': 92,
'*Pro Superior III* 🎁': 94,
'*Pro Superior II* 🎁': 96,
'*Pro Superior I* 🎁': 98,
'*King V* 💻': 100,
'*King IV* 💻': 102,
'*King III* 💻': 104,
'*King II* 💻': 106,
'*King I* 💻': 108,
'*Pro King V* 🎒': 110,
'*Pro King IV* 🎒': 112,
'*Pro King III* 🎒': 114,
'*Pro King II* 🎒': 116,
'*Pro King I* 🎒': 118,
'*Invisible V* 🔔': 120,
'*Invisible IV* 🔔': 122,
'*Invisible III* 🔔': 124,
'*Invisible II* 🔔': 126,
'*Invisible I* 🔔': 128,
'*Rentaro V* 🌌': 130,
'*Rentaro IV* 🌌': 132,
'*Rentaro III* 🌌': 134,
'*Rentaro II* 🌌': 136,
'*Rentaro I* 🌌': 138,
'*Premium V* 🏆': 140,
'*Premium IV* 🏆': 145,
'*Premium III* 🏆': 150,
'*Premium II* 🏆': 155,
'*Premium I* 🏆': 160,
'*King Rentaro V* 👑': 170,
'*King Rentaro IV* 👑': 185,
'*King Rentaro III* 👑': 200,
'*King Rentaro II* 👑': 250,
'*King Rentaro I* 👑': 300
}

let handler = m => m
handler.before = async function (m, { conn }) {
        let user = db.data.users[m.sender]
        let level = user.level
        let role = (Object.entries(roles).sort((a, b) => b[1] - a[1]).find(([, minLevel]) => level >= minLevel) || Object.entries(roles)[0])[0]
        user.role = role
        return !0

}
export default handler 
